"use server";

import { randomUUID } from "node:crypto";
import { revalidatePath } from "next/cache";
import { requireRole } from "@/lib/auth";
import { createAdminClient } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";
import { getInviteRedirectUrl } from "@/lib/site-url";

type ActionResult = { error?: string; success?: string };
const staffRoles = ["CASHIER", "KITCHEN_ADMIN"] as const;
function text(value: FormDataEntryValue | null, label: string) { const result = String(value ?? "").trim(); if (!result) throw new Error(`${label} is required.`); return result; }
function tenantId(context: Awaited<ReturnType<typeof requireRole>>) { if (!context.profile.tenant_id) throw new Error("Your account is not attached to a tenant."); return context.profile.tenant_id; }
function price(value: FormDataEntryValue | null) { const result = text(value, "Price"); if (!/^\d{1,12}(?:\.\d{1,2})?$/.test(result)) throw new Error("Price must be a non-negative amount with up to two decimals."); return result; }

export async function inviteStaff(formData: FormData): Promise<ActionResult> {
  const context = await requireRole(["STORE_OWNER"]); const id = tenantId(context); let authId: string | null = null;
  try { const email=text(formData.get("email"),"Email").toLowerCase(); const name=text(formData.get("fullName"),"Full name"); const role=text(formData.get("role"),"Role"); if(!staffRoles.includes(role as typeof staffRoles[number])) throw new Error("Only Cashier or Kitchen Admin staff can be invited."); const admin=createAdminClient(); const invitation=await admin.auth.admin.inviteUserByEmail(email,{data:{full_name:name},redirectTo:await getInviteRedirectUrl()}); if(invitation.error||!invitation.data.user) throw new Error(invitation.error?.message??"Staff invitation failed."); authId=invitation.data.user.id; const supabase=await createClient(); const profile=await supabase.from("profiles").insert({id:authId,tenant_id:id,role,full_name:name,email,is_active:true}); if(profile.error) throw new Error(profile.error.message); revalidatePath("/store/staff"); return {success:"Staff invitation sent."}; }
  catch(error){ if(authId){try{await createAdminClient().auth.admin.deleteUser(authId)}catch(cleanup){console.error("Staff Auth cleanup failed",cleanup)}} return {error:error instanceof Error?error.message:"Staff invitation failed."}; }
}

export async function setStaffActive(formData: FormData): Promise<ActionResult> { const context=await requireRole(["STORE_OWNER"]); try { const supabase=await createClient(); const updated=await supabase.from("profiles").update({is_active:String(formData.get("isActive"))==="true"}).eq("id",text(formData.get("userId"),"Staff user")).eq("tenant_id",tenantId(context)).in("role",["CASHIER","KITCHEN_ADMIN"]); if(updated.error)throw new Error(updated.error.message); revalidatePath("/store/staff"); return {success:"Staff status updated."}; } catch(error){return {error:error instanceof Error?error.message:"Staff status update failed."};} }

export async function createCategory(formData: FormData): Promise<ActionResult> { const context=await requireRole(["STORE_OWNER"]); try {const supabase=await createClient(); const result=await supabase.from("categories").insert({tenant_id:tenantId(context),name:text(formData.get("name"),"Category name")});if(result.error)throw new Error(result.error.message);revalidatePath("/store/categories");return {success:"Category created."};}catch(error){return {error:error instanceof Error?error.message:"Category could not be created."};} }
export async function updateCategory(formData: FormData): Promise<ActionResult> { const context=await requireRole(["STORE_OWNER"]); try {const supabase=await createClient(); const result=await supabase.from("categories").update({name:text(formData.get("name"),"Category name"),is_active:String(formData.get("isActive"))!=="false"}).eq("id",text(formData.get("categoryId"),"Category")).eq("tenant_id",tenantId(context));if(result.error)throw new Error(result.error.message);revalidatePath("/store/categories");return {success:"Category updated."};}catch(error){return {error:error instanceof Error?error.message:"Category could not be updated."};} }

async function categoryForTenant(categoryId: string, id: string) { const supabase=await createClient(); const category=await supabase.from("categories").select("id").eq("id",categoryId).eq("tenant_id",id).maybeSingle(); if(category.error||!category.data)throw new Error("Category does not belong to this tenant."); }
export async function toggleCategory(formData: FormData): Promise<ActionResult> { const context=await requireRole(["STORE_OWNER"]); try {const supabase=await createClient();const categoryId=text(formData.get("categoryId"),"Category");const category=await supabase.from("categories").select("is_active").eq("id",categoryId).eq("tenant_id",tenantId(context)).maybeSingle();if(category.error||!category.data)throw new Error("Category not found.");const result=await supabase.from("categories").update({is_active:!category.data.is_active}).eq("id",categoryId).eq("tenant_id",tenantId(context));if(result.error)throw new Error(result.error.message);revalidatePath("/store/categories");revalidatePath("/store/products");return {success:category.data.is_active?"Category archived.":"Category activated."};}catch(error){return {error:error instanceof Error?error.message:"Category status could not be updated."};} }
export async function createProduct(formData: FormData): Promise<ActionResult> { const context=await requireRole(["STORE_OWNER"]); try {const id=tenantId(context);const categoryId=text(formData.get("categoryId"),"Category");await categoryForTenant(categoryId,id);const supabase=await createClient();const result=await supabase.from("products").insert({tenant_id:id,category_id:categoryId,name:text(formData.get("name"),"Product name"),description:String(formData.get("description")??"").trim()||null,price:price(formData.get("price")),image_url:String(formData.get("imageUrl")??"").trim()||null,is_active:true});if(result.error)throw new Error(result.error.message);revalidatePath("/store/products");revalidatePath("/store/dashboard");return {success:"Product created."};}catch(error){return {error:error instanceof Error?error.message:"Product could not be created."};} }
export async function updateProduct(formData: FormData): Promise<ActionResult> { const context=await requireRole(["STORE_OWNER"]); try {const id=tenantId(context), productId=text(formData.get("productId"),"Product");const categoryId=text(formData.get("categoryId"),"Category");await categoryForTenant(categoryId,id);const supabase=await createClient();const result=await supabase.from("products").update({category_id:categoryId,name:text(formData.get("name"),"Product name"),description:String(formData.get("description")??"").trim()||null,price:price(formData.get("price")),image_url:String(formData.get("imageUrl")??"").trim()||null,is_active:String(formData.get("isActive"))!=="false",updated_at:new Date().toISOString()}).eq("id",productId).eq("tenant_id",id);if(result.error)throw new Error(result.error.message);revalidatePath("/store/products");revalidatePath("/store/dashboard");return {success:"Product updated."};}catch(error){return {error:error instanceof Error?error.message:"Product could not be updated."};} }

export async function toggleProduct(formData: FormData): Promise<ActionResult> { const context=await requireRole(["STORE_OWNER"]); try {const id=tenantId(context), productId=text(formData.get("productId"),"Product");const supabase=await createClient();const product=await supabase.from("products").select("is_active").eq("id",productId).eq("tenant_id",id).maybeSingle();if(product.error||!product.data)throw new Error("Product not found.");const result=await supabase.from("products").update({is_active:!product.data.is_active,updated_at:new Date().toISOString()}).eq("id",productId).eq("tenant_id",id);if(result.error)throw new Error(result.error.message);revalidatePath("/store/products");revalidatePath("/store/dashboard");return {success:product.data.is_active?"Product archived.":"Product activated."};}catch(error){return {error:error instanceof Error?error.message:"Product status could not be updated."};} }
export async function createTable(formData: FormData): Promise<ActionResult> { const context=await requireRole(["STORE_OWNER"]); try {const supabase=await createClient();const result=await supabase.from("tables").insert({tenant_id:tenantId(context),table_number:text(formData.get("tableNumber"),"Table number")});if(result.error)throw new Error(result.error.message);revalidatePath("/store/tables");revalidatePath("/store/dashboard");return {success:"Table created."};}catch(error){return {error:error instanceof Error?error.message:"Table could not be created."};} }
export async function updateTable(formData: FormData): Promise<ActionResult> { const context=await requireRole(["STORE_OWNER"]); try {const supabase=await createClient();const result=await supabase.from("tables").update({table_number:text(formData.get("tableNumber"),"Table number"),status:String(formData.get("status"))==="ACTIVE"?"ACTIVE":"INACTIVE"}).eq("id",text(formData.get("tableId"),"Table")).eq("tenant_id",tenantId(context));if(result.error)throw new Error(result.error.message);revalidatePath("/store/tables");revalidatePath("/store/dashboard");return {success:"Table updated."};}catch(error){return {error:error instanceof Error?error.message:"Table could not be updated."};} }
export async function regenerateTableToken(formData: FormData): Promise<ActionResult> { const context=await requireRole(["STORE_OWNER"]); try {const supabase=await createClient();const result=await supabase.from("tables").update({public_token:randomUUID().replaceAll("-","")}).eq("id",text(formData.get("tableId"),"Table")).eq("tenant_id",tenantId(context));if(result.error)throw new Error(result.error.message);revalidatePath("/store/tables");return {success:"Public ordering identity regenerated."};}catch(error){return {error:error instanceof Error?error.message:"Table identity could not be regenerated."};} }
