"use server";
import { revalidatePath } from "next/cache";
import { requireRole } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
function value(fd:FormData,key:string){return String(fd.get(key)??"").trim();}
function json(fd:FormData,key:string){try{return JSON.parse(value(fd,key));}catch{throw new Error("Invalid JSON input.");}}
async function tenant(roles:("STORE_OWNER"|"KITCHEN_ADMIN")[]){const c=await requireRole(roles);if(!c.profile.tenant_id)throw new Error("Tenant is missing.");return c.profile.tenant_id;}
export type InventoryActionResult={ok:boolean;message:string};
function inventoryActionMessage(code:string|undefined,details:string|undefined){if(code==="PGRST202")return "Fungsi database belum tersedia. Minta administrator memeriksa migrasi inventory pada project Supabase production.";if(code==="42501"||details?.includes("not authorized"))return "Akun ini tidak memiliki izin untuk melakukan tindakan tersebut.";if(details?.includes("supplier unavailable"))return "Supplier tidak aktif atau tidak tersedia untuk toko ini.";if(details?.includes("inventory item unavailable"))return "Salah satu bahan tidak aktif atau tidak tersedia untuk toko ini.";if(details?.includes("product not found"))return "Produk tidak ditemukan pada toko ini.";if(details?.includes("recipe unit does not match"))return "Satuan bahan tidak sesuai dengan satuan inventori.";if(details?.includes("invalid recipe quantity")||details?.includes("invalid request quantity"))return "Jumlah harus lebih besar dari nol.";if(details?.includes("duplicate request item"))return "Bahan yang sama hanya boleh ditambahkan satu kali.";if(details?.includes("request cannot be empty"))return "Tambahkan setidaknya satu bahan ke permintaan.";if(details?.includes("idempotency key payload conflict"))return "Permintaan ini sudah dikirim dengan isi berbeda. Muat ulang halaman sebelum mencoba lagi.";return "Data tidak dapat disimpan. Periksa pilihan bahan, jumlah, dan statusnya, lalu coba lagi.";}
export async function createInventoryItem(fd:FormData){const id=await tenant(["STORE_OWNER"]);const name=value(fd,"name");const unit=value(fd,"unit");const minimum=Number(value(fd,"minimumStock")||0);const target=value(fd,"targetStock");if(!name||minimum<0||target&&Number(target)<minimum)throw new Error("Invalid inventory item.");const db=await createClient();const r=await db.from("inventory_items").insert({tenant_id:id,name,unit,minimum_stock:minimum,target_stock:target?Number(target):null});if(r.error)throw new Error(r.error.message);revalidatePath("/store/inventory");revalidatePath("/kitchen/inventory");}
export async function toggleInventoryItem(fd:FormData){const id=await tenant(["STORE_OWNER"]);const item=value(fd,"inventoryItemId");const active=value(fd,"isActive")==="true";const r=await (await createClient()).from("inventory_items").update({is_active:!active,updated_at:new Date().toISOString()}).eq("id",item).eq("tenant_id",id);if(r.error)throw new Error(r.error.message);revalidatePath("/store/inventory");revalidatePath("/kitchen/inventory");}
export async function adjustInventory(fd:FormData){await tenant(["STORE_OWNER","KITCHEN_ADMIN"]);const r=await (await createClient()).rpc("record_inventory_adjustment",{p_inventory_item_id:value(fd,"inventoryItemId"),p_movement_type:value(fd,"movementType"),p_quantity:Number(value(fd,"quantity")),p_reason:value(fd,"reason"),p_idempotency_key:value(fd,"idempotencyKey")});if(r.error)throw new Error(r.error.message);revalidatePath("/store/inventory");revalidatePath("/kitchen/inventory");}
export async function saveRecipe(fd:FormData):Promise<InventoryActionResult>{await tenant(["STORE_OWNER"]);let items:unknown;try{items=json(fd,"items");}catch{return {ok:false,message:"Daftar bahan tidak valid. Pilih setidaknya satu bahan dan isi jumlahnya."};}try{const r=await (await createClient()).rpc("save_recipe",{p_product_id:value(fd,"productId"),p_items:items,p_is_active:value(fd,"isActive")!=="false"});if(r.error)return {ok:false,message:inventoryActionMessage(r.error.code,r.error.message)};revalidatePath("/store/recipes");revalidatePath("/kitchen/recipes");return {ok:true,message:"Recipe berhasil disimpan."};}catch{return {ok:false,message:"Recipe belum dapat disimpan. Periksa koneksi lalu coba lagi."};}}
export async function createSupplier(fd:FormData){const id=await tenant(["STORE_OWNER"]);const r=await (await createClient()).from("suppliers").insert({tenant_id:id,name:value(fd,"name"),contact_person:value(fd,"contactPerson")||null,phone:value(fd,"phone")||null,email:value(fd,"email")||null,address:value(fd,"address")||null,notes:value(fd,"notes")||null});if(r.error)throw new Error(r.error.message);revalidatePath("/store/suppliers");}
export async function toggleSupplier(fd:FormData){const id=await tenant(["STORE_OWNER"]);const active=value(fd,"isActive")==="true";const r=await (await createClient()).from("suppliers").update({is_active:!active,updated_at:new Date().toISOString()}).eq("id",value(fd,"supplierId")).eq("tenant_id",id);if(r.error)throw new Error(r.error.message);revalidatePath("/store/suppliers");}
export async function linkSupplierItem(fd:FormData){const id=await tenant(["STORE_OWNER"]);const db=await createClient();const r=await db.from("supplier_inventory_items").insert({tenant_id:id,supplier_id:value(fd,"supplierId"),inventory_item_id:value(fd,"inventoryItemId"),purchase_unit:value(fd,"purchaseUnit"),conversion_quantity:value(fd,"conversionQuantity")?Number(value(fd,"conversionQuantity")):null,last_known_price:value(fd,"lastKnownPrice")?Number(value(fd,"lastKnownPrice")):null,is_preferred:value(fd,"isPreferred")==="true"});if(r.error)throw new Error(r.error.message);revalidatePath("/store/suppliers");}
export async function createPurchaseRequest(fd:FormData):Promise<InventoryActionResult>{await tenant(["STORE_OWNER","KITCHEN_ADMIN"]);let items:unknown;try{items=json(fd,"items");}catch{return {ok:false,message:"Daftar bahan tidak valid. Pilih setidaknya satu bahan dan isi jumlahnya."};}try{const r=await (await createClient()).rpc("create_purchase_request",{p_items:items,p_supplier_id:value(fd,"supplierId")||null,p_reason:value(fd,"reason"),p_notes:value(fd,"notes"),p_idempotency_key:value(fd,"idempotencyKey")});if(r.error)return {ok:false,message:inventoryActionMessage(r.error.code,r.error.message)};revalidatePath("/store/purchase-requests");revalidatePath("/kitchen/purchase-requests");return {ok:true,message:"Purchase request berhasil dikirim."};}catch{return {ok:false,message:"Purchase request belum dapat dikirim. Periksa koneksi lalu coba lagi."};}}
export async function setPurchaseRequestStatus(fd:FormData){await tenant(["STORE_OWNER"]);const r=await (await createClient()).rpc("set_purchase_request_status",{p_request_id:value(fd,"requestId"),p_next_status:value(fd,"status")});if(r.error)throw new Error(r.error.message);revalidatePath("/store/purchase-requests");revalidatePath("/kitchen/purchase-requests");}
export async function createPurchaseOrder(fd:FormData){await tenant(["STORE_OWNER"]);const r=await (await createClient()).rpc("create_purchase_order",{p_supplier_id:value(fd,"supplierId"),p_items:json(fd,"items"),p_request_id:value(fd,"requestId")||null});if(r.error)throw new Error(r.error.message);revalidatePath("/store/purchase-orders");}
export async function setPurchaseOrderStatus(fd:FormData){await tenant(["STORE_OWNER"]);const r=await (await createClient()).rpc("set_purchase_order_status",{p_purchase_order_id:value(fd,"purchaseOrderId"),p_next_status:value(fd,"status")});if(r.error)throw new Error(r.error.message);revalidatePath("/store/purchase-orders");}
export async function receivePurchaseOrder(fd:FormData){await tenant(["STORE_OWNER"]);const r=await (await createClient()).rpc("receive_purchase_order",{p_purchase_order_id:value(fd,"purchaseOrderId"),p_items:json(fd,"items"),p_idempotency_key:value(fd,"idempotencyKey"),p_notes:value(fd,"notes")});if(r.error)throw new Error(r.error.message);revalidatePath("/store/purchase-orders");revalidatePath("/store/inventory");}
