import Link from "next/link";
import { SubscriptionAssignment } from "@/components/platform/subscription-assignment";
import { getPlatformData, getPlatformPlans } from "@/lib/platform";
import { formatDateTime, formatRemainingTime } from "@/lib/subscriptions";

export default async function SubscriptionsPage() {
  const [data, plans] = await Promise.all([getPlatformData(), getPlatformPlans()]);
  return <><div className="page-heading-row"><div><p className="eyebrow">Platform</p><h1 className="page-title">Subscriptions</h1><p className="page-intro">Assign plans and manage tenant subscription lifecycle. Expiry is calculated from the plan duration.</p></div><Link className="secondary-button button-link" href="/platform/plans">Manage plans</Link></div><SubscriptionAssignment tenants={data.tenants.map(({ id, name, slug }) => ({ id, name, slug }))} plans={plans.filter((plan) => plan.is_active)}/>{data.subscriptions.length === 0 ? <div className="plain-empty large-empty"><h2>No subscriptions yet.</h2><p>Subscriptions appear after a tenant is created.</p></div> : <div className="table-wrap platform-table"><table><thead><tr><th>Tenant</th><th>Plan</th><th>Amount</th><th>Start</th><th>Expiry</th><th>Status</th><th>Remaining</th><th>Record</th></tr></thead><tbody>{data.subscriptions.map((subscription) => <tr key={subscription.id}><td>{subscription.tenant?.name ?? "Unknown tenant"}</td><td>{subscription.plan_name}</td><td>{new Intl.NumberFormat("id-ID", { style: "currency", currency: subscription.currency }).format(subscription.amount)}</td><td>{formatDateTime(subscription.started_at)}</td><td>{formatDateTime(subscription.expires_at)}</td><td><span className={`status status-${subscription.status.toLowerCase()}`}>{subscription.status.replaceAll("_", " ")}</span></td><td>{formatRemainingTime(subscription.expires_at)}</td><td>{subscription.is_current ? "Current" : "History"}</td></tr>)}</tbody></table></div>}</>;
}
