"use client";
import { useRouter } from "next/navigation";
import { useEffect, useState, useTransition } from "react";
import { cancelCashierOrder, confirmCashPayment } from "@/app/cashier/actions";
import type { CashierOrder } from "@/lib/cashier";
import { createClient } from "@/lib/supabase/client";

const money = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
export function CashierOrderList({ orders, filter, tenantId, enableLiveUpdates = true }: { orders: CashierOrder[]; filter?: "pending" | "paid" | "all"; tenantId: string; enableLiveUpdates?: boolean }) {
  const [pending, start] = useTransition(); const [notice, setNotice] = useState<string | null>(null); const router = useRouter(); useEffect(() => { if (!enableLiveUpdates) return; const supabase = createClient(); const channel = supabase.channel("cashier-orders:" + tenantId).on("postgres_changes", { event: "*", schema: "public", table: "orders", filter: "tenant_id=eq." + tenantId }, () => router.refresh()).subscribe(); const timer = window.setInterval(() => router.refresh(), 30000); return () => { window.clearInterval(timer); void supabase.removeChannel(channel); }; }, [enableLiveUpdates, router, tenantId]);
  const visible = filter === "pending" ? orders.filter((order) => order.payment_status === "PENDING" && order.order_status === "PENDING_PAYMENT") : filter === "paid" ? orders.filter((order) => order.payment_status === "PAID") : orders;
  async function run(action: (form: FormData) => Promise<{ error?: string; success?: string }>, id: string) { const form = new FormData(); form.set("orderId", id); const result = await action(form); setNotice(result.error ?? result.success ?? null); if (!result.error) router.refresh(); }
  return <>{notice && <p className="form-success cashier-notice">{notice}</p>}{visible.length === 0 ? <div className="plain-empty">No matching orders.</div> : <div className="cashier-list">{visible.map((order) => <article className="cashier-order" key={order.id}><div className="cashier-order-head"><div><strong>#{order.order_number}</strong><span className="cashier-type">{order.order_type === "DINE_IN" ? `Table ${order.table_number ?? "â€”"}` : "TAKEAWAY"}</span></div><span className={`status status-${order.payment_status.toLowerCase()}`}>{order.payment_status}</span></div><div className="cashier-order-meta"><span>{order.items.reduce((sum, item) => sum + item.quantity, 0)} items</span><strong>{money.format(Number(order.total))}</strong><span>{order.payment_method ?? "â€”"}</span></div><div className="cashier-items">{order.items.map((item, index) => <div key={`${item.product_name_snapshot}-${index}`}><span>{item.quantity} Ã— {item.product_name_snapshot}{item.notes && <small>{item.notes}</small>}</span><span>{money.format(Number(item.line_total))}</span></div>)}</div>{order.order_status === "PENDING_PAYMENT" && <div className="cashier-actions">{order.payment_method === "CASH" && <button className="primary-button compact" disabled={pending} onClick={() => start(() => { void run(confirmCashPayment, order.id); })}>Confirm cash</button>}<button className="secondary-button" disabled={pending} onClick={() => start(() => { void run(cancelCashierOrder, order.id); })}>Cancel</button></div>}{order.order_status === "QUEUED" && <p className="queue-note">Paid and queued for kitchen.</p>}</article>)}</div>}</>;
}
